export const REQUEST_MAP_PLOTS = 'REQUEST_MAP_PLOTS';
export const RECEIVE_MAP_PLOTS_SUCCESS = 'RECEIVE_MAP_PLOTS_SUCCESS';
export const RECEIVE_MAP_PLOTS_FAILURE = 'RECEIVE_MAP_PLOTS_FAILURE';

export const REQUEST_SAVE_MAP_PLOTS = 'REQUEST_SAVE_MAP_PLOTS';
export const RECEIVE_SAVE_MAP_PLOTS_SUCCESS = 'RECEIVE_SAVE_MAP_PLOTS_SUCCESS';
export const RECEIVE_SAVE_MAP_PLOTS_FAILURE = 'RECEIVE_SAVE_MAP_PLOTS_FAILURE';
